# Generated by Django 5.2.10 on 2026-01-30 05:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Material name (e.g., PET Plastic, Cotton Waste, E-Waste)', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of the material type')),
                ('base_price_per_kg', models.DecimalField(decimal_places=2, help_text='Base price per kilogram in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_a_multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='Price multiplier for Grade A (e.g., 1.5 = 150% of base)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_b_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Price multiplier for Grade B (e.g., 1.0 = 100% of base)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade_c_multiplier', models.DecimalField(decimal_places=2, default=0.7, help_text='Price multiplier for Grade C (e.g., 0.7 = 70% of base)', max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('co2_saved_per_kg', models.FloatField(default=0.0, help_text='CO2 saved per kg when recycled (in kg CO2)', validators=[django.core.validators.MinValueValidator(0)])),
                ('icon', models.CharField(blank=True, default='bi-recycle', help_text='Bootstrap icon class (e.g., bi-recycle)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this material is currently accepting listings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['is_active'], name='marketplace_is_acti_81da2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='WasteListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short title for the listing', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the waste material')),
                ('weight', models.FloatField(help_text='Weight in kilograms', validators=[django.core.validators.MinValueValidator(0.1)])),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for the entire lot in ₹', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.CharField(choices=[('A', 'Grade A - Premium Quality'), ('B', 'Grade B - Standard Quality'), ('C', 'Grade C - Basic Quality')], default='B', help_text='Quality grade', max_length=1)),
                ('trust_score', models.IntegerField(default=50, help_text='Verification trust score (0-100) from OpenCV', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_verified', models.BooleanField(default=False, help_text='Whether listing has been verified (trust >= 50%)')),
                ('verification_notes', models.TextField(blank=True, help_text='Notes from verification process')),
                ('image1', models.ImageField(blank=True, help_text='Primary image', null=True, upload_to='listings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('image2', models.ImageField(blank=True, help_text='Additional image', null=True, upload_to='listings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('image3', models.ImageField(blank=True, help_text='Additional image', null=True, upload_to='listings/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('video', models.FileField(blank=True, help_text='Video demonstration (optional)', null=True, upload_to='listings/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mov'])])),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('address', models.TextField(blank=True, help_text='Detailed pickup address')),
                ('status', models.CharField(choices=[('LISTED', 'Listed'), ('MATCHED', 'Matched with Buyer'), ('SOLD', 'Sold'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='LISTED', help_text='Current listing status', max_length=20)),
                ('co2_saved', models.FloatField(default=0.0, help_text='Total CO2 that will be saved if recycled (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this listing expires', null=True)),
                ('material', models.ForeignKey(help_text='Type of material', on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='marketplace.material')),
                ('seller', models.ForeignKey(help_text='User who created this listing', limit_choices_to={'role': 'GENERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='waste_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waste Listing',
                'verbose_name_plural': 'Waste Listings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'is_verified'], name='marketplace_status_5552bc_idx'), models.Index(fields=['material', 'grade'], name='marketplace_materia_16fea9_idx'), models.Index(fields=['city', 'state'], name='marketplace_city_b1a1f5_idx'), models.Index(fields=['seller'], name='marketplace_seller__1e917b_idx')],
            },
        ),
    ]
