# Generated by Django 5.0 on 2026-01-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_wastelisting_gemini_grading_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastelisting',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate from geolocation', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='wastelisting',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate from geolocation', max_digits=9, null=True),
        ),
    ]
