# Generated by Django 5.0 on 2026-01-30 07:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_amount', models.DecimalField(decimal_places=2, help_text="Buyer's offered price", max_digits=10)),
                ('delivery_address', models.TextField(help_text='Delivery address provided by buyer')),
                ('contact_number', models.CharField(help_text='Buyer contact number', max_length=15)),
                ('notes', models.TextField(blank=True, help_text='Additional notes from buyer')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Seller Approval'), ('ACCEPTED', 'Accepted - Awaiting Payment'), ('CONFIRMED', 'Payment Confirmed'), ('REJECTED', 'Rejected by Seller'), ('CANCELLED', 'Cancelled by Buyer'), ('COMPLETED', 'Transaction Completed')], default='PENDING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Payment Pending'), ('PROCESSING', 'Processing Payment'), ('COMPLETED', 'Payment Completed'), ('FAILED', 'Payment Failed'), ('REFUNDED', 'Payment Refunded')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='Mock payment transaction hash', max_length=64)),
                ('seller_notes', models.TextField(blank=True, help_text='Notes from seller (reason for rejection, etc.)')),
                ('buyer', models.ForeignKey(help_text='Buyer making the offer', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='The listing being purchased', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='marketplace.wastelisting')),
                ('seller', models.ForeignKey(help_text='Seller receiving the offer', on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='transaction_buyer_i_053873_idx'), models.Index(fields=['seller', '-created_at'], name='transaction_seller__8cf6c4_idx'), models.Index(fields=['listing', '-created_at'], name='transaction_listing_b78ac0_idx'), models.Index(fields=['status'], name='transaction_status_71abbb_idx')],
            },
        ),
    ]
