# Generated by Django 5.0 on 2026-01-30 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(help_text='Sequential block number (0 = genesis block)')),
                ('previous_hash', models.CharField(default='0000000000000000000000000000000000000000000000000000000000000000', help_text='SHA-256 hash of previous block (genesis = all zeros)', max_length=64)),
                ('current_hash', models.CharField(help_text='SHA-256 hash of this block (calculated on save)', max_length=64, unique=True)),
                ('action', models.CharField(choices=[('CREATED', 'Listing Created'), ('VERIFIED', 'AI Quality Verified'), ('LISTED', 'Listed on Marketplace'), ('PURCHASED', 'Purchased by Buyer'), ('COLLECTED', 'Collected by Worker'), ('DELIVERED', 'Delivered to Buyer'), ('RECYCLED', 'Recycled/Processed'), ('CANCELLED', 'Listing Cancelled'), ('UPDATED', 'Listing Updated')], help_text='What action occurred', max_length=20)),
                ('actor_name', models.CharField(help_text='Name of actor (preserved even if user deleted)', max_length=200)),
                ('actor_role', models.CharField(blank=True, help_text='Role of actor at time of action', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('INVALIDATED', 'Invalidated')], default='CONFIRMED', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this block was created (immutable)')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contextual data (trust_score, price, etc.)')),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this action')),
                ('is_valid', models.BooleanField(default=True, help_text='Whether this block passes hash validation')),
                ('actor', models.ForeignKey(blank=True, help_text='Who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provenance_actions', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(help_text='The waste listing this block belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='provenance_blocks', to='marketplace.wastelisting')),
            ],
            options={
                'verbose_name': 'Provenance Block',
                'verbose_name_plural': 'Provenance Blocks',
                'ordering': ['listing', 'block_number'],
                'indexes': [models.Index(fields=['listing', 'block_number'], name='provenance__listing_ee850f_idx'), models.Index(fields=['current_hash'], name='provenance__current_2150c7_idx'), models.Index(fields=['timestamp'], name='provenance__timesta_e4ba72_idx')],
                'unique_together': {('listing', 'block_number')},
            },
        ),
    ]
